// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/get-company-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
var get_company_overview_default = defineTool({
  name: "get_company_overview",
  title: "Get company overview",
  description: "Get a high-level overview of GreenMixes: what the company does, its headline stats, and its positioning.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const overview = {
      name: "GreenMixes Ltd",
      tagline: "Carbon-negative concrete",
      location: "Cambridge, UK",
      summary: "GreenMixes turns biomass residues into biochar-based concrete admixtures, locking carbon permanently into building structures. The Carbon-to-Concrete platform drops into existing batching workflows with no capex and no downtime.",
      origin: "Founded by materials scientists from the University of Cambridge, who solved the biochar-cement binding problem to enable significantly higher cement replacement without compromising performance.",
      stats: [
        { value: "8%", label: "of global CO\u2082 is from cement" },
        { value: ">15%", label: "cement replacement enabled" },
        { value: "2-3\xD7", label: "higher biochar loading" },
        { value: "0", label: "workflow changes needed" }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: overview
    };
  }
});

// src/lib/mcp/tools/get-technology.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
var get_technology_default = defineTool2({
  name: "get_technology",
  title: "Get technology process",
  description: "Get the steps of the GreenMixes Carbon-to-Concrete process, from biomass residues to carbon locked in construction.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const technology = {
      headline: "From waste to carbon sink",
      description: "The Carbon-to-Concrete platform integrates seamlessly into existing construction workflows\u2014no capex, no disruption.",
      steps: [
        { step: 1, title: "Biomass Residues", description: "Agricultural waste containing sequestered carbon" },
        { step: 2, title: "Biochar Production", description: "Pyrolysis converts waste into stable carbon" },
        {
          step: 3,
          title: "GreenMixes Processing",
          description: "Proprietary binders create high-performance admixtures"
        },
        { step: 4, title: "Construction", description: "Carbon locked permanently into building structures" }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(technology, null, 2) }],
      structuredContent: technology
    };
  }
});

// src/lib/mcp/tools/get-audiences.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
var get_audiences_default = defineTool3({
  name: "get_audiences",
  title: "Get target audiences",
  description: "Get the customer segments GreenMixes serves and the value proposition for each (manufacturers, construction, governments, carbon credit buyers).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const audiences = [
      {
        title: "Concrete Manufacturers",
        description: "Swap in our admixture\u2014same batching process, same plant, radically lower carbon footprint. No capex, no downtime."
      },
      {
        title: "Real Estate & Construction",
        description: "Every cubic metre poured becomes a verified carbon sink. Hit net-zero targets on projects already in your pipeline."
      },
      {
        title: "Governments & Regulators",
        description: "Decarbonise public infrastructure with a solution validated at the University of Cambridge and ready for national-scale deployment."
      },
      {
        title: "Carbon Credit Buyers",
        description: "Access durable, physically locked carbon removal credits\u2014quantifiable per building, auditable per tonne."
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(audiences, null, 2) }],
      structuredContent: { audiences }
    };
  }
});

// src/lib/mcp/tools/get-team-and-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
var get_team_and_contact_default = defineTool4({
  name: "get_team_and_contact",
  title: "Get team and contact details",
  description: "Get the GreenMixes founding team and the public contact details for business enquiries.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      team: [
        { name: "Callon Peate", role: "PhD Student, University of Cambridge" },
        { name: "Dr. Dushanth Seevaratnam", role: "PhD Chemical Engineering, University of Cambridge" }
      ],
      contact: {
        email: "callon@greenmixes.com",
        location: "Cambridge, UK"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "biochar-built-better",
  title: "Biochar Built Better",
  version: "0.1.0",
  instructions: "Public information tools for GreenMixes, a Cambridge-founded carbon-negative concrete company. Use `get_company_overview` for positioning and headline stats, `get_technology` for the Carbon-to-Concrete process steps, `get_audiences` for customer segments, and `get_team_and_contact` for the founding team and contact details.",
  tools: [get_company_overview_default, get_technology_default, get_audiences_default, get_team_and_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
